"""Fixtures and test environment for AiStorage End-to-End Acceptance Tests (Tasks 9.1 - 9.5).

Adheres strictly to:
- openspec/changes/establish-aistorage-phase1/tasks.md §9 (9.1 - 9.5)
- Design D10 (Split, Claim, Reference, Continuation, Consolidation)
- Each session runs in its own resident container (resident/run.sh)
- Sole source of truth for handover/reference is the reader interface (AgoraReader)
- Committer runs locally as committer-test (python -m aistorage.committer run --config config/committer.e2e.json)
- Configuration generated by scripts/e2e_setup.py: config/committer.e2e.json and reader.e2e.json
- Missing settings FAIL immediately (NEVER skip)
- Model comes from AISTORAGE_E2E_MODEL (default opencode/space-bunny-free; no Claude)
- E2E uses a **test profile** (spec "期 1 的身分種類": Mac opencode 之外另有測試用
  profile) and the test inbox / test read view created by scripts/e2e_setup.py；
  不使用正式的 profile 秘密目錄或正式收件匣。

API 路徑（opencode 1.18.32，依 https://opencode.ai/docs/server/ 與 1.7d）：
- 建立 Session：`POST /session`
- 送訊息（等回覆）：`POST /session/{id}/message`（body 的 parts 是 Part 陣列）
- 讀回工具呼叫：`docker exec <container> opencode export <session_id>`（1.7a）

**新 Session 一律由 `agora checkout` ＋ `agora-opencode load` 建出**（ADR 0010、
`docs/design/agora-session-operations.md`）：AI 不再自己 claim。容器端用
`ResidentContainerHandle.checkout_with_commits()` 與 `opencode_load()` 驅動，
開頭的位元組相同由 `wire_prefix()`（spike 的 `export_prefix_bytes`）比對。
"""

from __future__ import annotations

import json
import os
from pathlib import Path
import re
import subprocess
import sys
import threading
import time
from typing import Any, Callable, Generator, Iterator, Sequence
import urllib.request

import pytest

from aistorage.clock import SystemClock
from aistorage.reader import AgoraReader
from aistorage.reader.client import ReadViewClient
from aistorage.reader.config import ReaderConfig


REPO_ROOT = Path(__file__).resolve().parents[2]

# e2e 環境鎖住在 scripts/e2e_setup.py（可執行的腳本，但函式可以直接用）
if str(REPO_ROOT / "scripts") not in sys.path:
    sys.path.insert(0, str(REPO_ROOT / "scripts"))
from e2e_setup import (  # noqa: E402 - 需要先補 sys.path
    E2EEnvLocked,
    acquire_e2e_lock,
    e2e_lock_holder,
    release_e2e_lock,
)
RUN_SH = REPO_ROOT / "resident" / "run.sh"

CONFIG_DIR = REPO_ROOT / "config"
COMMITTER_E2E_CONFIG = CONFIG_DIR / "committer.e2e.json"
READER_E2E_CONFIG = CONFIG_DIR / "reader.e2e.json"

ENV_COMMITTER_E2E = "AISTORAGE_E2E_COMMITTER_CONFIG"
ENV_READER_E2E = "AISTORAGE_E2E_READER_CONFIG"
DEFAULT_E2E_MODEL = "opencode/space-bunny-free"

#: 測試用 profile（E-P4）。正式目錄是 ~/.config/aistorage/resident/mac-opencode；
#: e2e 一律用**另一個秘密根目錄**（預設 ~/.config/aistorage/resident-e2e），
#: 由 scripts/e2e_setup.py 佈置；正式目錄一律拒絕。
DEFAULT_E2E_PROFILE = "mac-opencode-test"
ENV_E2E_PROFILE = "AISTORAGE_E2E_PROFILE"
ENV_E2E_SECRETS_ROOT = "AISTORAGE_E2E_SECRETS_ROOT"
DEFAULT_E2E_SECRETS_ROOT = Path.home() / ".config" / "aistorage" / "resident-e2e"
PRODUCTION_SECRETS_ROOT = Path.home() / ".config" / "aistorage" / "resident"

#: 提交流程在本機執行時要用的測試憑證（只以路徑引用，絕不讀取內容）。
AISTORAGE_HOME = Path.home() / ".config" / "aistorage"
E2E_RCLONE_CONF = AISTORAGE_HOME / "rclone-committer-test.conf"
E2E_PIN_KEY = AISTORAGE_HOME / "pin-test.key"
E2E_KNOWN_HOSTS = REPO_ROOT / "config" / "github_known_hosts"
E2E_WORKER_CONF = AISTORAGE_HOME / "rclone-worker.conf"
ENV_E2E_RCLONE_CONF = "AISTORAGE_E2E_RCLONE_CONF"
ENV_E2E_PIN_KEY = "AISTORAGE_E2E_PIN_KEY"
ENV_E2E_KNOWN_HOSTS = "AISTORAGE_E2E_KNOWN_HOSTS"
ENV_E2E_WORKER_CONF = "AISTORAGE_E2E_WORKER_CONF"
#: 設成 1 就不拿 e2e 環境鎖（只有自己知道在做什麼時才用；CI 上兩份 job 共用
#: 同一個環境時，其中一份必須這樣，否則第二份會被自己的鎖擋住）
ENV_E2E_NO_LOCK = "AISTORAGE_E2E_NO_LOCK"

#: 容器內必要檔名（run.sh 的白名單）；缺任何一個 container 起不來。
REQUIRED_PROFILE_FILES = ("rclone-worker.conf", "sa-reader.json", "signing.key", "reader.json")

#: 模型回覆（含工具呼叫）的等待上限；免費模型可能很慢。
#:
#: 必須**大於工具自己的逾時**（`agora_handoff`／`agora checkout` 內部等讀取視圖
#: 15 分鐘），否則 HTTP 先斷，會看到沒有資訊的 socket timeout，而不是工具那句
#: 「還沒被收進去」。9.1 實測：提交流程接連中止時，工具會等滿 15 分鐘。
MESSAGE_TIMEOUT_S = 1800.0
#: 容器啟動（colima + opencode serve）的上限。
CONTAINER_READY_TIMEOUT_S = 180.0
#: 背景提交流程的輪詢間隔。
COMMITTER_POLL_INTERVAL_S = 5.0


class MissingE2ESetting(RuntimeError):
    """端到端驗收測試缺少設定檔時拋出此例外（依 PM 規範：必須 FAIL，不可 skip）。"""


def _require_file(path: Path, what: str, env_override: str | None = None) -> Path:
    target = Path(os.environ[env_override]) if env_override and os.environ.get(env_override) else path
    if not target.is_file():
        raise MissingE2ESetting(
            f"E2E 驗收測試需要 {what}（路徑: {target}），但該檔不存在。"
            "請先執行 scripts/e2e_setup.py 產生端到端測試環境設定檔。"
            "（依據 PM 指示：設定缺少時必須 FAIL，不可使用 pytest.skip 掩蓋未通過驗收）。"
        )
    return target


@pytest.fixture(scope="session")
def e2e_settings() -> Iterator[dict[str, Any]]:
    """載入端到端驗收測試所需設定；缺檔時立即 FAIL。

    一開始就取得 e2e 環境鎖：連「設定不完整、驗證就失敗」的情況都要算有人在用，
    否則別條線會在這場 e2e 剛起步時把環境 teardown 掉。
    """
    secrets_root = Path(
        os.environ.get(ENV_E2E_SECRETS_ROOT, str(DEFAULT_E2E_SECRETS_ROOT))
    )
    take_lock = not os.environ.get(ENV_E2E_NO_LOCK)
    if take_lock:
        try:
            acquire_e2e_lock(action="pytest e2e", secrets_root=secrets_root)
        except E2EEnvLocked as e:
            raise MissingE2ESetting(
                f"另一場 e2e 正在用這個環境：{e}\n"
                "請等它結束再跑（不要用 --force-unlock，除非確定對方已經卡死）。"
            ) from e
    try:
        yield from _e2e_settings_locked(secrets_root)
    finally:
        if take_lock:
            release_e2e_lock(secrets_root)


def _e2e_settings_locked(secrets_root: Path) -> Iterator[dict[str, Any]]:
    committer_cfg_path = _require_file(COMMITTER_E2E_CONFIG, "Committer E2E 設定檔", ENV_COMMITTER_E2E)
    reader_cfg_path = _require_file(READER_E2E_CONFIG, "Reader E2E 設定檔", ENV_READER_E2E)

    with open(committer_cfg_path, "r", encoding="utf-8") as f:
        committer_cfg = json.load(f)

    with open(reader_cfg_path, "r", encoding="utf-8") as f:
        reader_cfg = json.load(f)

    profile = os.environ.get(ENV_E2E_PROFILE)
    if not profile:
        mapping = reader_cfg.get("inbox_folder_ids")
        if isinstance(mapping, dict) and len(mapping) == 1:
            # e2e_setup 只用一個 profile；不要猜，直接用它登記的唯一 profile
            profile = next(iter(mapping))
        else:
            profile = DEFAULT_E2E_PROFILE
    if secrets_root.resolve() == PRODUCTION_SECRETS_ROOT.resolve():
        raise MissingE2ESetting(
            "E2E 禁止使用正式的 profile 秘密根目錄 "
            f"({PRODUCTION_SECRETS_ROOT})；測試 profile 要放在另一個根目錄。"
        )
    profile_dir = secrets_root / profile
    if not profile_dir.is_dir():
        raise MissingE2ESetting(
            f"E2E 需要測試 profile 的秘密目錄（路徑: {profile_dir}），但不存在。"
            "請先執行 scripts/e2e_setup.py 佈置測試 profile"
            f"（{ENV_E2E_PROFILE}／{ENV_E2E_SECRETS_ROOT} 可覆寫）。"
        )
    model = os.environ.get("AISTORAGE_E2E_MODEL", DEFAULT_E2E_MODEL)
    provider = model.split("/", 1)[0] if "/" in model else "opencode"
    # 免金鑰的 provider（opencode zen 的免費模型匿名可用、依 IP 限流）不需要
    # `llm-<provider>.key`。判斷和 resident/run.sh、resident/image/entrypoint.sh
    # 、scripts/e2e_setup.py 用同一個環境變數與同一份預設清單。
    keyless = (os.environ.get("AISTORAGE_KEYLESS_PROVIDERS") or "opencode").split()
    required = REQUIRED_PROFILE_FILES + (
        () if provider in keyless else (f"llm-{provider}.key",)
    )
    missing = [name for name in required if not (profile_dir / name).is_file()]
    if missing:
        raise MissingE2ESetting(
            f"E2E 測試 profile {profile_dir} 缺少必要檔案：{', '.join(missing)}；"
            "請執行 scripts/e2e_setup.py。"
        )
    if profile == "mac-opencode":
        raise MissingE2ESetting(
            "E2E 禁止使用正式的 mac-opencode profile（spec「期 1 的身分種類」"
            "要求另有測試用 profile）；請重跑 scripts/e2e_setup.py 或把 "
            f"{ENV_E2E_PROFILE} 指到測試用 profile。"
        )

    rclone_conf = Path(os.environ.get(ENV_E2E_RCLONE_CONF, str(E2E_RCLONE_CONF)))
    pin_key = Path(os.environ.get(ENV_E2E_PIN_KEY, str(E2E_PIN_KEY)))
    known_hosts = Path(os.environ.get(ENV_E2E_KNOWN_HOSTS, str(E2E_KNOWN_HOSTS)))
    worker_conf = Path(os.environ.get(ENV_E2E_WORKER_CONF, str(profile_dir / "rclone-worker.conf")))
    for path, what in (
        (rclone_conf, "提交流程的 rclone 設定"),
        (pin_key, "pin repo 的 deploy key"),
        (known_hosts, "GitHub known_hosts"),
    ):
        if not path.is_file():
            raise MissingE2ESetting(f"E2E 需要{what}（路徑: {path}），但不存在。")

    settings = {
        "committer_config_path": committer_cfg_path,
        "committer_config": committer_cfg,
        "reader_config_path": reader_cfg_path,
        "reader_config": reader_cfg,
        "model": os.environ.get("AISTORAGE_E2E_MODEL", DEFAULT_E2E_MODEL),
        "profile": profile,
        "secrets_root": secrets_root,
        "profile_dir": profile_dir,
        "rclone_conf": rclone_conf,
        "pin_key": pin_key,
        "known_hosts": known_hosts,
        "worker_conf": worker_conf,
        # 收件匣 id 直接從 reader.e2e.json 取（conftest 已驗過 profile 對得上）。
        # 容器裡的 /secrets/reader.json 是 profile 目錄的**檔案掛載**：那個檔案
        # 一旦被刪（或被別條線重跑 setup 換掉），掛載會變成空目錄，
        # 同步器就會回「找不到收件匣 folder id」。所以這裡明確帶進去。
        "inbox_folder_id": _e2e_inbox_folder_id(reader_cfg, profile),
    }

    yield settings


def _e2e_inbox_folder_id(reader_cfg: dict[str, Any], profile: str) -> str:
    mapping = reader_cfg.get("inbox_folder_ids")
    if not isinstance(mapping, dict) or not mapping.get(profile):
        raise MissingE2ESetting(
            "reader.e2e.json 的 inbox_folder_ids 沒有測試 profile "
            f"{profile!r}（請重跑 scripts/e2e_setup.py）"
        )
    return str(mapping[profile])


#: 整場 e2e 的提交流程結果統計：outcome → 次數。outcome 是
#: `SUCCESS` 或 `ABORTED(step:Code)`。測試結束時印出來（見 pytest_sessionfinish）。
COMMITTER_OUTCOMES: dict[str, int] = {}


def _record_committer_outcome(report_stdout: str) -> str:
    m = re.search(r"\]\s+(SUCCESS|ABORTED\([^)]*\))", report_stdout or "")
    outcome = m.group(1) if m else "UNKNOWN"
    COMMITTER_OUTCOMES[outcome] = COMMITTER_OUTCOMES.get(outcome, 0) + 1
    return outcome


def pytest_sessionfinish(session, exitstatus):  # noqa: ARG001 - pytest  hook
    """整場 e2e 跑完把提交流程的結果統計印出來（PM 要的「跑了幾輪、中止幾次」）。"""
    if COMMITTER_OUTCOMES:
        total = sum(COMMITTER_OUTCOMES.values())
        print("\n[e2e] 提交流程結果統計（共 %d 輪）: %s" % (total, COMMITTER_OUTCOMES))


def _committer_env(e2e_settings: dict[str, Any]) -> dict[str, str]:
    """提交流程在本機執行時需要的環境（秘密只以路徑傳遞）。"""
    env = dict(os.environ)
    env["AISTORAGE_RCLONE_CONF"] = str(e2e_settings["rclone_conf"])
    env["AISTORAGE_PIN_KEY"] = str(e2e_settings["pin_key"])
    env["AISTORAGE_PIN_KNOWN_HOSTS"] = str(e2e_settings["known_hosts"])
    env["RCLONE_CONFIG"] = str(e2e_settings["rclone_conf"])
    return env


@pytest.fixture
def run_committer(e2e_settings) -> Callable[..., subprocess.CompletedProcess]:
    """在本機以 committer-test 身分執行提交流程 (python -m aistorage.committer run)。

    失敗時 raise（呼叫端不必再檢查 returncode）。`config_path` 可以覆寫設定檔
    （撤銷金鑰等安全測試用），`env_extra` 可以疊加環境變數。
    """
    default_cfg_path = str(e2e_settings["committer_config_path"])
    default_env = _committer_env(e2e_settings)

    def _execute(
        *,
        config_path: str | None = None,
        env_extra: dict[str, str] | None = None,
        timeout_s: float = 900.0,
    ) -> subprocess.CompletedProcess:
        cfg_path = config_path or default_cfg_path
        cmd = ["uv", "run", "python", "-m", "aistorage.committer", "run", "--config", cfg_path]
        env = dict(default_env)
        if env_extra:
            env.update(env_extra)
        res = subprocess.run(
            cmd, cwd=str(REPO_ROOT), capture_output=True, text=True, env=env, timeout=timeout_s
        )
        outcome = _record_committer_outcome(res.stdout)
        print(f"[committer] {outcome}")
        if res.returncode != 0:
            raise RuntimeError(
                f"Committer 執行失敗 (rc={res.returncode}, {outcome}):\n"
                f"STDOUT: {res.stdout[-2000:]}\nSTDERR: {res.stderr[-2000:]}"
            )
        last_line = res.stdout.strip().splitlines()[-1] if res.stdout.strip() else ""
        if "SUCCESS" not in last_line:
            raise RuntimeError(f"Committer 沒有回報 SUCCESS：{last_line or res.stdout[-500:]}")
        return res

    return _execute


@pytest.fixture
def e2e_reader(e2e_settings) -> AgoraReader:
    """透過產生的 reader.e2e.json 建立正式的 AgoraReader 讀取介面。

    E-P2：SA 金鑰是 JSON（`sa-reader.json`），要用 `ServiceAccountToken`，不是
    `RcloneConfToken`（那是 rclone conf）；`ReadViewClient` 與 `AgoraReader` 都要
    `clock`。
    """
    from aistorage.drive import HttpDriveClient
    from aistorage.drive.sa_auth import ServiceAccountToken

    cfg_path = e2e_settings["reader_config_path"]
    reader_cfg = ReaderConfig.load(cfg_path)
    clock = SystemClock()
    drive = HttpDriveClient(ServiceAccountToken(reader_cfg.sa_key_path))
    rv_client = ReadViewClient(drive, reader_cfg, clock=clock)
    return AgoraReader(rv_client, clock=clock)


class ExportFailed(RuntimeError):
    """`opencode export` 失敗（截斷、形狀不符…）——與 AiStorage 的行為無關。"""


class ModelDidNotComply(RuntimeError):
    """模型沒有照指示呼叫工具（環境／模型能力問題，不是系統錯誤）。

    E-M3：這種情況要和「工具跑了但失敗」區分開來，方便依隊員順序換模型重跑。
    """


def _report_outcome(report: Any) -> str:
    """提交流程 run report 最後一行 → 一個可統計的結果字串。

    形如 `[RunReport 01M3…] SUCCESS | counts: …` 或
    `[RunReport 01M3…] ABORTED(pins.write_pending:WriteError) | counts: …`。
    """
    out = getattr(report, "stdout", "") or ""
    for line in reversed(out.strip().splitlines()):
        m = re.search(r"\]\s+(SUCCESS|ABORTED\([^)]*\))", line)
        if m:
            return m.group(1)
    return "UNKNOWN"


class ResidentContainerHandle:
    """管理個別住民容器的生命週期與互動。

    - `prompt()` 走 opencode 的 HTTP API（E-P1）：`POST /session` 建立 Session，
      再 `POST /session/{id}/message` 送訊息並等回覆。
    - `export()` 走 `docker exec <name> opencode export <id>`（1.7a：必須明示 id）。
    - `sync_once()` 在容器內跑同步器；提交流程由測試在本機執行（不觸發 GitHub）。
    """

    def __init__(
        self,
        name: str,
        port: int,
        *,
        work_dir: Path,
        secrets_root: Path,
        profile: str,
        model: str,
        log_path: Path,
        inbox_folder_id: str = "",
    ):
        self.inbox_folder_id = inbox_folder_id
        self.name = name
        self.port = port
        self.work_dir = work_dir  # run.sh 真正的 /work 來源（AISTORAGE_WORK_ROOT）
        self.secrets_root = secrets_root
        self.profile = profile
        self.model = model
        self.log_path = log_path
        self.proc: subprocess.Popen | None = None
        self._log_file: Any = None
        #: 最近一次 prompt_with_commits 期間提交流程的結果統計
        #: （`{"SUCCESS": 3, "ABORTED(pins.write_pending:WriteError)": 2}`）
        self.committer_tally: dict[str, int] = {}

    @property
    def api_url(self) -> str:
        return f"http://127.0.0.1:{self.port}"

    # ── HTTP API（E-P1）──────────────────────────────────────────────────

    def _request(
        self, path: str, *, method: str = "GET", payload: dict | None = None,
        timeout: float = 60.0,
    ) -> Any:
        url = f"{self.api_url}{path}?directory=/work"
        data = json.dumps(payload).encode("utf-8") if payload is not None else None
        headers = {"Accept": "application/json"}
        if data is not None:
            headers["Content-Type"] = "application/json"
        req = urllib.request.Request(url, data=data, headers=headers, method=method)
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            body = resp.read()
        if not body:
            return None
        return json.loads(body.decode("utf-8"))

    def wait_ready(self, timeout: float = CONTAINER_READY_TIMEOUT_S) -> None:
        """等待容器內 opencode serve 就緒。"""
        deadline = time.time() + timeout
        last_error = "（尚未連上）"
        while time.time() < deadline:
            if self.proc is not None and self.proc.poll() is not None:
                raise RuntimeError(
                    f"住民容器 {self.name} 提前結束（rc={self.proc.returncode}）；"
                    f"log: {self.log_path}"
                )
            try:
                self._request("/session", timeout=5.0)
                return
            except Exception as e:  # noqa: BLE001 - 啟動期間任何錯誤都只代表還沒好
                last_error = f"{type(e).__name__}: {e}"
                time.sleep(1.0)
        tail = ""
        try:
            tail = self.log_path.read_text(encoding="utf-8", errors="replace")[-1000:]
        except OSError:
            pass
        raise TimeoutError(
            f"住民容器 {self.name} 在 {timeout} 秒內未就緒 (port {self.port}): "
            f"{last_error}\n--- run.sh log ---\n{tail}"
        )

    def create_session(self, title: str | None = None) -> str:
        """建立一個新的主 Session，回傳 opencode 原生 id。"""
        payload: dict[str, Any] = {}
        if title:
            payload["title"] = title
        data = self._request("/session", method="POST", payload=payload)
        sid = data.get("id") if isinstance(data, dict) else None
        if not isinstance(sid, str) or not sid:
            raise RuntimeError(f"POST /session 沒有回傳 id: {data!r}")
        return sid

    def send(self, session_id: str, text: str, *, timeout_s: float = MESSAGE_TIMEOUT_S) -> dict:
        """送一則使用者訊息並等模型回覆（POST /session/{id}/message）。"""
        payload = {"parts": [{"type": "text", "text": text}]}
        data = self._request(
            f"/session/{session_id}/message", method="POST", payload=payload, timeout=timeout_s
        )
        if not isinstance(data, dict):
            raise RuntimeError(f"POST /session/{session_id}/message 回應不是物件: {data!r}")
        return data

    def prompt(
        self, text: str, *, session_id: str | None = None,
        timeout_s: float = MESSAGE_TIMEOUT_S,
    ) -> tuple[str, dict]:
        """建立（或沿用）Session 並送訊息；回傳 (session_id, 回應)。"""
        sid = session_id or self.create_session()
        return sid, self.send(sid, text, timeout_s=timeout_s)

    def prompt_with_commits(
        self,
        text: str,
        run_committer: Callable[..., Any],
        *,
        session_id: str | None = None,
        timeout_s: float = MESSAGE_TIMEOUT_S,
    ) -> tuple[str, dict]:
        """送訊息，同時在本機反覆執行提交流程（模擬 workflow 被觸發）。

        `agora_handoff`／`aistorage_split` 等工具內部會「同步 → 觸發提交 → 等讀取
        介面看得到」；e2e 不提供 PAT（不觸發 GitHub），所以由測試扮演提交流程，
        直到工具回覆為止。工具本身逾時（15 分鐘）之前必須讓它看得到。
        """
        sid = session_id or self.create_session()
        stop = threading.Event()
        errors: list[str] = []
        tally: dict[str, int] = {}

        def _loop() -> None:
            while not stop.is_set():
                try:
                    report = run_committer()
                    errors.clear()
                    # 這一輪已由 run_committer 記進全域統計
                    tally[_report_outcome(report)] = tally.get(_report_outcome(report), 0) + 1
                except Exception as e:  # noqa: BLE001 - 記錄後繼續重試
                    errors.append(str(e))
                stop.wait(COMMITTER_POLL_INTERVAL_S)

        thread = threading.Thread(target=_loop, name=f"committer-{self.name}", daemon=True)
        thread.start()
        try:
            response = self.send(sid, text, timeout_s=timeout_s)
        finally:
            stop.set()
            thread.join(timeout=60.0)
        # 提交流程每一輪的結果都留下來：A 線目前有兩種會中止的情況
        # （verify_after_push 的 MismatchError、write_pending 的 WriteError），
        # 測試要能回答「這一輪中止了幾次」而不是只看最後有沒有成功。
        self.committer_tally = dict(tally)
        print(f"[e2e:{self.name}] 提交流程 {tally or '（沒有跑成）'}"
              + (f" 例外：{errors[-1][:160]}" if errors else ""))
        return sid, response

    def revert(self, session_id: str, message_id: str) -> None:
        """撤銷到某則訊息（1.7c：`POST /session/{id}/revert`，等效 /undo）。"""
        self._request(
            f"/session/{session_id}/revert",
            method="POST",
            payload={"messageID": message_id},
            timeout=30.0,
        )

    def list_sessions(self) -> list[dict[str, Any]]:
        """取得容器內全部的 Session（含子 Session）。"""
        data = self._request("/session", timeout=15.0)
        if isinstance(data, dict):
            data = data.get("sessions") or data.get("data") or []
        if not isinstance(data, list):
            raise RuntimeError(f"GET /session 回應不是清單: {data!r}")
        return data

    def get_session(self, session_id: str) -> dict[str, Any]:
        data = self._request(f"/session/{session_id}", timeout=15.0)
        if not isinstance(data, dict):
            raise RuntimeError(f"GET /session/{session_id} 回應不是物件: {data!r}")
        return data

    # ── docker exec ──────────────────────────────────────────────────────

    def exec_in(
        self,
        args: Sequence[str],
        *,
        env: dict[str, str] | None = None,
        timeout_s: float = 300.0,
        check: bool = True,
    ) -> subprocess.CompletedProcess:
        """在容器內執行指令（除錯與測試用）。"""
        cmd = ["docker", "exec"]
        for key, value in (env or {}).items():
            cmd += ["-e", f"{key}={value}"]
        cmd += [self.name, *args]
        res = subprocess.run(cmd, capture_output=True, text=True, timeout=timeout_s)
        if check and res.returncode != 0:
            raise RuntimeError(
                f"docker exec 失敗 (rc={res.returncode}): {' '.join(args)}\n"
                f"STDOUT: {res.stdout[-1000:]}\nSTDERR: {res.stderr[-1000:]}"
            )
        return res

    def export(self, session_id: str) -> dict[str, Any]:
        """`opencode export <id>` 的原生匯出（1.7a：必須明示 id）。

        匯出失敗要**明確說是匯出失敗**，不要讓它看起來像 AiStorage 的系統錯誤。
        9.1 e2e 實測：容器裡的對話被免費模型回覆塞到很大時，`opencode export`
        吐出被截斷的 JSON（`Unterminated string`），而呼叫端（`assert_tool_called`）
        剛好也在用匯出，於是整場 e2e 看起來像「工具被呼叫了但都失敗」——
        實際上只是匯出讀不到。
        """
        res = self.exec_in(["opencode", "export", session_id], timeout_s=180.0)
        try:
            data = json.loads(res.stdout)
        except ValueError as e:
            tail = res.stdout[-200:].replace("\n", "\\n")
            raise ExportFailed(
                f"匯出這個 Session 失敗（session={session_id}）：{e}\n"
                f"輸出長度 {len(res.stdout)} bytes，結尾是 …{tail}\n"
                "這是 opencode 匯出端的問題（常見於對話很長時輸出被截斷），"
                "不是 AiStorage 的錯誤，也無法據此判斷 AI 有沒有呼叫工具。"
            ) from None
        if not isinstance(data, dict) or "messages" not in data:
            raise ExportFailed(
                f"匯出這個 Session 失敗（session={session_id}）："
                f"形狀不符（缺 messages，拿到 {type(data).__name__}）"
            )
        return data

    def tool_parts(self, session_id: str) -> list[dict[str, Any]]:
        """匯出裡全部的 tool part 摘要（依出現順序）。"""
        out: list[dict[str, Any]] = []
        for msg in self.export(session_id).get("messages", []):
            info = msg.get("info") if isinstance(msg, dict) else None
            for part in msg.get("parts", []) if isinstance(msg, dict) else []:
                if not isinstance(part, dict) or part.get("type") != "tool":
                    continue
                state = part.get("state") if isinstance(part.get("state"), dict) else {}
                out.append(
                    {
                        "tool": part.get("tool"),
                        "call_id": part.get("callID"),
                        "message_id": info.get("id") if isinstance(info, dict) else None,
                        "status": state.get("status"),
                        "input": state.get("input"),
                        "output": state.get("output"),
                        "error": state.get("error"),
                    }
                )
        return out

    def tool_env(self) -> dict[str, str]:
        """容器內跑 CLI（`agora`、`agora-opencode`、同步器）要帶的環境變數。

        環境變數在 entrypoint 才 export，docker exec 拿不到，所以明確帶入；
        祕密只以容器內路徑引用。收件匣 id 由測試端帶（`/secrets/reader.json` 是
        檔案掛載，被換掉時會變成空目錄）。
        """
        env = {
            "AISTORAGE_PROFILE": self.profile,
            "AISTORAGE_SIGNING_KEY": "/secrets/signing.key",
            "AISTORAGE_READER_CONFIG": "/secrets/reader.json",
            "AISTORAGE_SA_KEY": "/secrets/sa-reader.json",
            "AISTORAGE_RCLONE_CONF": "/tmp/aistorage/rclone.conf",
        }
        if self.inbox_folder_id:
            env["AISTORAGE_INBOX_FOLDER_ID"] = self.inbox_folder_id
        return env

    def sync_once(
        self, session_ids: Sequence[str] | None = None
    ) -> subprocess.CompletedProcess:
        """在容器內跑一輪同步器（同步器 daemon 每 10 分鐘才跑一次，測試要明確觸發）。"""
        args = ["python", "-m", "aistorage.syncer", "opencode", "once"]
        for sid in session_ids or ():
            args += ["--session", sid]
        return self.exec_in(args, env=self.tool_env(), timeout_s=300.0)

    # ── agora CLI（`agora`／`agora-opencode`）──────────────────────────────

    def agora(
        self,
        args: Sequence[str],
        *,
        check: bool = True,
        timeout_s: float = 1800.0,
    ) -> subprocess.CompletedProcess:
        """在容器內跑 `agora <args>`（設計文件的單一指令入口）。

        逾時上限與 `MESSAGE_TIMEOUT_S` 同值：`agora checkout` 內部會等讀取介面
        確認（15 分鐘），必須大於它，否則只會看到沒有資訊的 socket timeout。
        """
        return self.exec_in(["agora", *args], env=self.tool_env(),
                            timeout_s=timeout_s, check=check)

    def checkout(
        self,
        startpoints: Sequence[str],
        out_dir: str,
        *,
        task: str | None = None,
        extra_args: Sequence[str] = (),
        check: bool = True,
    ) -> subprocess.CompletedProcess:
        """在容器內跑 `agora checkout <起點>… -o <out_dir>`。

        `out_dir` 要寫成容器內的路徑；`/work` 就是 `self.work_dir`，所以宿主機
        上讀得到同一份起點包（`read_package` 驗 sha 用）。
        """
        args = ["checkout", *startpoints, "-o", out_dir]
        if task:
            args += ["--task", task]
        args += list(extra_args)
        return self.agora(args, check=check)

    def checkout_with_commits(
        self,
        startpoints: Sequence[str],
        out_dir: str,
        run_committer: Callable[..., Any],
        *,
        task: str | None = None,
        extra_args: Sequence[str] = (),
    ) -> subprocess.CompletedProcess:
        """跑 `agora checkout`，**同時**在本機反覆執行提交流程。

        checkout 會放一筆認領進收件匣（那筆認領**自己帶著**預留給新 session 的
        空紀錄），然後等讀取介面確認。e2e 不提供 PAT（不觸發 GitHub），所以
        提交流程由測試扮演——這正是 ADR 0007 的「寫入者以讀取介面判斷完成」。

        **預設不檢查 exit code**：被拒（`ClaimRejected` rc=6、長度超限 rc=2）
        也要看得到 stdout／stderr，由測試自己斷言。
        """
        stop = threading.Event()
        errors: list[str] = []
        tally: dict[str, int] = {}

        def _loop() -> None:
            while not stop.is_set():
                try:
                    report = run_committer()
                    errors.clear()
                    outcome = _report_outcome(report)
                    tally[outcome] = tally.get(outcome, 0) + 1
                except Exception as e:  # noqa: BLE001 - 記錄後繼續重試
                    errors.append(str(e))
                stop.wait(COMMITTER_POLL_INTERVAL_S)

        thread = threading.Thread(target=_loop, name=f"committer-{self.name}",
                                  daemon=True)
        thread.start()
        try:
            result = self.checkout(startpoints, out_dir, task=task,
                                   extra_args=extra_args, check=False)
        finally:
            stop.set()
            thread.join(timeout=60.0)
        self.committer_tally = dict(tally)
        print(f"[e2e:{self.name}] checkout 期間提交流程 {tally or '（沒有跑成）'}"
              + (f" 例外：{errors[-1][:160]}" if errors else ""))
        return result

    def opencode_load(
        self, package_dir: str, *, workdir: str = "/work", check: bool = True
    ) -> str:
        """`agora-opencode load <起點包>`：回傳新 session id（來源端，不帶前綴）。

        這裡只匯入（`opencode import`）；**開不開 agent 由呼叫者決定**——測試
        用容器內的 opencode API 在那個新 session 上繼續（等於 `opencode
        --session <id>`）。
        """
        res = self.exec_in(
            ["agora-opencode", "load", package_dir, "-C", workdir],
            env=self.tool_env(), timeout_s=600.0, check=check,
        )
        return res.stdout.strip().splitlines()[-1] if res.stdout.strip() else ""

    # ── 生命週期 ─────────────────────────────────────────────────────────

    def stop(self) -> None:
        """停止並強制移除容器。"""
        subprocess.run(["docker", "rm", "-f", self.name], capture_output=True)
        if self.proc:
            self.proc.terminate()
            try:
                self.proc.wait(timeout=10)
            except subprocess.TimeoutExpired:
                self.proc.kill()
        if self._log_file is not None:
            try:
                self._log_file.close()
            except OSError:
                pass
            self._log_file = None

    def container_exists(self) -> bool:
        """容器是否還存在（persistence 測試用來確認真的刪掉了）。"""
        res = subprocess.run(
            ["docker", "inspect", self.name], capture_output=True, text=True
        )
        return res.returncode == 0


def _free_port() -> int:
    """找一個目前沒有人在用的本機 port。"""
    import socket

    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
        sock.bind(("127.0.0.1", 0))
        return int(sock.getsockname()[1])


@pytest.fixture
def resident_pool(e2e_settings, tmp_path) -> Generator[Callable[..., ResidentContainerHandle], None, None]:
    """建立並追蹤測試中啟動的所有住民容器，並於測試結束時清理。

    E-P4：用測試 profile（預設 `mac-opencode-test`），祕密目錄由
    `AISTORAGE_RESIDENT_ROOT` 指向測試用根目錄；正式 profile 一律拒絕。
    """
    active_containers: list[ResidentContainerHandle] = []
    # **工作目錄必須在 colima 看得見的掛載點底下**。
    # colima 只把 `$HOME` 與 `/tmp/colima` 掛進 VM（實測：`/private/var/folders/...`
    # 也就是 pytest 的 tmp_path，bind mount 會直接報
    # "bind source path does not exist"）。所以 work_root 放在
    # `~/.local/share/aistorage/work/e2e`；log 留在 tmp_path。
    # 測試結束時容器會被移除，/work 的內容隨之消失。
    work_root = Path(
        os.environ.get("AISTORAGE_E2E_WORK_ROOT",
                       str(Path.home() / ".local" / "share" / "aistorage" / "work" / "e2e"))
    )
    work_root.mkdir(parents=True, exist_ok=True)
    log_root = tmp_path / "container-logs"
    log_root.mkdir(parents=True, exist_ok=True)

    def _spawn(name: str, *, port_offset: int = 0) -> ResidentContainerHandle:
        profile = e2e_settings["profile"]
        model = e2e_settings["model"]
        port = _free_port() + port_offset
        work_dir = work_root / name

        env = dict(os.environ)
        env["AISTORAGE_RESIDENT_ROOT"] = str(e2e_settings["secrets_root"])
        env["AISTORAGE_WORK_ROOT"] = str(work_root)

        # 啟動 resident/run.sh 並發布 API 埠供測試驅動（E-P3：run.sh 在
        # --publish-api 時把容器內的 serve 綁到 0.0.0.0，否則連接埠轉發不到）。
        cmd = [
            str(RUN_SH),
            name,
            "--profile",
            profile,
            "--model",
            model,
            "--publish-api",
            str(port),
            "--no-tui",
        ]
        log_path = log_root / f"{name}.log"
        log_file = open(log_path, "w", encoding="utf-8")
        proc = subprocess.Popen(
            cmd, cwd=str(REPO_ROOT), stdout=log_file, stderr=subprocess.STDOUT, env=env
        )
        handle = ResidentContainerHandle(
            name=name,
            port=port,
            work_dir=work_dir,
            secrets_root=Path(e2e_settings["secrets_root"]),
            profile=profile,
            model=model,
            log_path=log_path,
            inbox_folder_id=str(e2e_settings.get("inbox_folder_id") or ""),
        )
        handle.proc = proc
        handle._log_file = log_file
        active_containers.append(handle)
        try:
            handle.wait_ready()
        except Exception:
            handle.stop()
            raise
        return handle

    try:
        yield _spawn
    finally:
        for c in active_containers:
            try:
                c.stop()
            except Exception:
                pass


def assert_tool_called(
    container: ResidentContainerHandle,
    session_id: str,
    tool: str,
    *,
    count: int | None = None,
    require_ok: bool = True,
) -> list[dict[str, Any]]:
    """從 opencode 匯出確認 AI 真的呼叫了某個工具（review 的共用 helper）。

    - 找不到任何呼叫 → `ModelDidNotComply`（模型沒照做；環境問題，可換模型重跑）。
    - 有呼叫但全部失敗（state.status == "error"）→ AssertionError（系統錯誤）。
    - `count` 有給時，確認成功次數不少於 count。
    """
    try:
        parts = [p for p in container.tool_parts(session_id) if p.get("tool") == tool]
    except ExportFailed as e:
        # 匯出讀不到 → 無法驗證。這不是「模型沒照做」，也不是「工具失敗」，
        # 別讓它看起來像 AiStorage 的錯誤。
        raise AssertionError(f"無法驗證 {tool} 有沒有被呼叫：{e}") from None
    if not parts:
        available = sorted({str(p.get("tool")) for p in container.tool_parts(session_id)})
        raise ModelDidNotComply(
            f"模型沒有呼叫工具 {tool}（session={session_id}）；"
            f"這次匯出裡看得到的工具：{available or '（一個都沒有）'}"
        )
    ok_parts = [p for p in parts if p.get("status") == "completed"]
    if require_ok and not ok_parts:
        errors = "; ".join(
            str(p.get("error") or p.get("output") or "")[:200] for p in parts
        )
        raise AssertionError(f"工具 {tool} 被呼叫了但都失敗（session={session_id}）：{errors}")
    if count is not None and len(ok_parts) < count:
        raise AssertionError(
            f"工具 {tool} 成功次數不足：預期 >= {count}，實際 {len(ok_parts)}"
        )
    return ok_parts or parts


# ---------------------------------------------------------------------------
# 共用小工具（測試檔一律用這些，不要各自重寫）
# ---------------------------------------------------------------------------


#: spike 的比對工具（`docs/spike/session-import.md`）。把一份 opencode 匯出檔的
#: 訊息序列重播成「送給模型的 messages 陣列」並序列化——這是「新 session 的
#: 開頭與原 session 位元組相同」這個量的**決定性來源**。
sys.path.insert(0, str(REPO_ROOT / "scripts" / "spike"))
from session_import_compare import export_prefix_bytes as _wire_prefix  # noqa: E402


def wire_prefix(export: dict[str, Any], upto_message_id: str | None = None) -> bytes:
    """送給模型的開頭（bytes）；`upto_message_id` 給就截到那則為止（含）。

    真實的 opencode 匯出檔帶 `callID`，所以用預設的 `tool_call_id_key="id"`：
    轉接器重編 id 時**不動** `callID`，兩邊算出來才會一樣——那正是位元組相同
    能成立的原因（spike Q2／Q3 實測）。
    """
    messages = list(export.get("messages") or [])
    if upto_message_id is not None:
        for position, message in enumerate(messages):
            if str((message.get("info") or {}).get("id")) == upto_message_id:
                messages = messages[: position + 1]
                break
        else:
            raise AssertionError(
                f"匯出裡沒有訊息 {upto_message_id}（實際有 {len(messages)} 則）"
            )
    return _wire_prefix({"messages": messages})


def export_message_ids(export: dict[str, Any]) -> list[str]:
    """匯出裡的訊息 id（依出現順序）。"""
    return [
        str((m.get("info") or {}).get("id"))
        for m in (export.get("messages") or [])
        if isinstance(m, dict)
    ]


def agora_session_id(oc_session_id: str, source: str = "opencode") -> str:
    """opencode 原生 id → Agora 的 Session id（`opencode:<id>`）。"""
    return f"{source}:{oc_session_id}"


def poll(
    fn: Callable[[], Any],
    *,
    timeout_s: float = 300.0,
    interval_s: float = 5.0,
    what: str = "條件",
) -> Any:
    """輪詢直到 fn() 回傳 truthy 或逾時；逾時 raise（附上最後一個錯誤）。

    過渡期的例外（讀取視圖還沒發佈、index 世代還在切換…）會被容忍並重試；
    逾時時把最後一個錯誤一起拋出來，訊息不會被吞掉。
    """
    deadline = time.time() + timeout_s
    last: Any = None
    last_error: BaseException | None = None
    while time.time() < deadline:
        try:
            last = fn()
            last_error = None
        except Exception as e:  # noqa: BLE001 - 過渡期的讀取錯誤：重試到逾時
            last = None
            last_error = e
        if last:
            return last
        time.sleep(interval_s)
    if last_error is not None:
        raise TimeoutError(
            f"等待逾時（{what}，{timeout_s}s）；最後的錯誤："
            f"{type(last_error).__name__}: {last_error}"
        ) from last_error
    raise TimeoutError(f"等待逾時（{what}，{timeout_s}s）；最後結果：{last!r}")


def session_snapshot(reader: AgoraReader, session_id: str) -> Any:
    """讀單一 Session 的最新視圖；不存在時回 None。"""
    try:
        return reader.get_session(session_id).value
    except KeyError:
        return None


def wait_session_sha(
    reader: AgoraReader,
    session_id: str,
    raw_sha256: str | None,
    *,
    timeout_s: float = 300.0,
) -> Any:
    """等到 Agora 的讀取視圖看到這個 Session（可指定特定快照雜湊）。"""
    def _check() -> Any:
        view = session_snapshot(reader, session_id)
        if view is None:
            return None
        if raw_sha256 is None or view.session.raw_sha256.lower() == raw_sha256.lower():
            return view
        return None

    return poll(
        _check,
        timeout_s=timeout_s,
        what=f"讀取視圖看到 {session_id}"
        + (f"@{raw_sha256[:12]}" if raw_sha256 else ""),
    )


def latest_raw_sha(container: ResidentContainerHandle, session_id: str) -> str:
    """目前容器裡這個 Session 匯出的內容雜湊（用來確認同步器已上傳新版）。"""
    import hashlib

    res = container.exec_in(["opencode", "export", session_id], timeout_s=180.0)
    return hashlib.sha256(res.stdout.encode("utf-8")).hexdigest().lower()


def read_rejection_rows(reader: AgoraReader) -> list[dict[str, Any]]:
    """讀取視圖裡的全部拒收紀錄（只有代碼，沒有內容）。"""
    db = reader._client.index()
    try:
        columns = [r[1] for r in db.execute("PRAGMA table_info(rejections)")]
        if not columns:
            return []
        cur = db.execute(f"SELECT {', '.join(columns)} FROM rejections")
        return [dict(zip(columns, row)) for row in cur.fetchall()]
    finally:
        db.close()


def wait_rejection(reader: AgoraReader, item_key: str) -> dict[str, Any]:
    """等到某個 item_key 的拒收紀錄出現在讀取視圖，回傳該列。"""
    def _check() -> dict[str, Any] | None:
        for row in read_rejection_rows(reader):
            if row.get("item_key") == item_key:
                return row
        return None

    return poll(_check, what=f"拒收紀錄 {item_key} 發佈")


@pytest.fixture(scope="session")
def e2e_drive(e2e_settings):
    """提交流程測試憑證的 Drive 用戶端（放未簽章項目／檢查收件匣用；只以路徑引用）。"""
    from aistorage.drive import HttpDriveClient, RcloneConfToken

    return HttpDriveClient(RcloneConfToken(e2e_settings["rclone_conf"]))


@pytest.fixture(scope="session")
def e2e_worker_drive(e2e_settings):
    """worker 憑證的 Drive 用戶端（安全測試：證明住民刪不了真本）。"""
    from aistorage.drive import HttpDriveClient, RcloneConfToken

    worker_conf = Path(e2e_settings["worker_conf"])
    if not worker_conf.is_file():
        raise MissingE2ESetting(
            f"E2E 需要 worker 的 rclone 設定（路徑: {worker_conf}）才能做權限隔離測試。"
        )
    return HttpDriveClient(RcloneConfToken(worker_conf))


@pytest.fixture
def e2e_signer(e2e_settings):
    """讀測試 profile 的簽章金鑰（只以路徑；金鑰本身不進 log）。"""
    from aistorage.syncer.core import Signer

    key_path = Path(e2e_settings["profile_dir"]) / "signing.key"
    return Signer.from_key_file(key_path, profile=e2e_settings["profile"])


@pytest.fixture
def revoked_registry_config(e2e_settings, tmp_path):
    """把測試 profile 的金鑰標成 revoked 的身分登錄檔＋對應的 committer 設定。

    回傳 committer 設定檔路徑；測試用它跑一輪提交流程，斷言以被撤銷金鑰簽章的
    項目被 unauthorized 拒收。
    """
    registry_path = Path(e2e_settings["committer_config"]["identity_registry_path"])
    if not registry_path.is_absolute():
        registry_path = REPO_ROOT / registry_path
    if not registry_path.is_file():
        raise MissingE2ESetting(f"找不到身分登錄檔：{registry_path}")
    registry = json.loads(registry_path.read_text(encoding="utf-8"))
    profile = e2e_settings["profile"]
    for key in registry["profiles"][profile]["signing_keys"]:
        key["status"] = "revoked"
        key["revoked_at"] = "2026-09-28T12:00:00Z"
    revoked_registry = tmp_path / "identity.revoked.json"
    revoked_registry.write_text(json.dumps(registry, indent=2), encoding="utf-8")

    cfg = dict(e2e_settings["committer_config"])
    cfg["identity_registry_path"] = str(revoked_registry)
    cfg_path = tmp_path / "committer.revoked.json"
    cfg_path.write_text(json.dumps(cfg, indent=2), encoding="utf-8")
    return cfg_path


@pytest.fixture(scope="session")
def e2e_inbox_folder_id(e2e_settings) -> str:
    """測試 profile 的收件匣 folder id（由 scripts/e2e_setup.py 寫進 reader 設定）。"""
    mapping = e2e_settings["reader_config"].get("inbox_folder_ids")
    if not isinstance(mapping, dict) or not mapping:
        raise MissingE2ESetting("reader.e2e.json 缺少 inbox_folder_ids")
    profile = e2e_settings["profile"]
    folder_id = mapping.get(profile)
    if not folder_id and len(mapping) == 1:
        folder_id = next(iter(mapping.values()))
    if not isinstance(folder_id, str) or not folder_id:
        raise MissingE2ESetting(
            f"reader.e2e.json 的 inbox_folder_ids 沒有測試 profile "
            f"'{profile}' 的條目（現有：{sorted(mapping)}）"
        )
    return folder_id
