"""Fixtures and test environment for AiStorage End-to-End Acceptance Tests (Tasks 9.1 - 9.5).

Adheres strictly to:
- openspec/changes/establish-aistorage-phase1/tasks.md §9 (9.1 - 9.5)
- Design D10 (Split, Claim, Reference, Continuation, Consolidation)
- Each session runs in its own resident container (resident/run.sh)
- Sole source of truth for handover/reference is the reader interface (AgoraReader)
- Committer runs locally as committer-test (python -m aistorage.committer run --config config/committer.e2e.json)
- Configuration generated by scripts/e2e_setup.py: config/committer.e2e.json and reader.e2e.json
- Missing settings FAIL immediately (NEVER skip)
- Model: opencode/space-bunny-free (no Claude)
"""

from __future__ import annotations

import json
import os
from pathlib import Path
import subprocess
import time
from typing import Any, Callable, Generator
import urllib.request
import pytest

from aistorage.reader import AgoraReader, ReadViewClient
from aistorage.reader.config import ReaderConfig


REPO_ROOT = Path(__file__).resolve().parents[2]
RUN_SH = REPO_ROOT / "resident" / "run.sh"

CONFIG_DIR = REPO_ROOT / "config"
COMMITTER_E2E_CONFIG = CONFIG_DIR / "committer.e2e.json"
READER_E2E_CONFIG = CONFIG_DIR / "reader.e2e.json"

ENV_COMMITTER_E2E = "AISTORAGE_E2E_COMMITTER_CONFIG"
ENV_READER_E2E = "AISTORAGE_E2E_READER_CONFIG"
DEFAULT_E2E_MODEL = "opencode/space-bunny-free"


class MissingE2ESetting(RuntimeError):
    """端到端驗收測試缺少設定檔時拋出此例外（依 PM 規範：必須 FAIL，不可 skip）。"""


def _require_file(path: Path, what: str, env_override: str | None = None) -> Path:
    target = Path(os.environ[env_override]) if env_override and os.environ.get(env_override) else path
    if not target.is_file():
        raise MissingE2ESetting(
            f"E2E 驗收測試需要 {what}（路徑: {target}），但該檔不存在。"
            "請先執行 scripts/e2e_setup.py 產生端到端測試環境設定檔。"
            "（依據 PM 指示：設定缺少時必須 FAIL，不可使用 pytest.skip 掩蓋未通過驗收）。"
        )
    return target


@pytest.fixture(scope="session")
def e2e_settings() -> dict[str, Any]:
    """載入端到端驗收測試所需設定；缺檔時立即 FAIL。"""
    committer_cfg_path = _require_file(COMMITTER_E2E_CONFIG, "Committer E2E 設定檔", ENV_COMMITTER_E2E)
    reader_cfg_path = _require_file(READER_E2E_CONFIG, "Reader E2E 設定檔", ENV_READER_E2E)

    with open(committer_cfg_path, "r", encoding="utf-8") as f:
        committer_cfg = json.load(f)

    with open(reader_cfg_path, "r", encoding="utf-8") as f:
        reader_cfg = json.load(f)

    return {
        "committer_config_path": committer_cfg_path,
        "committer_config": committer_cfg,
        "reader_config_path": reader_cfg_path,
        "reader_config": reader_cfg,
        "model": os.environ.get("AISTORAGE_E2E_MODEL", DEFAULT_E2E_MODEL),
    }


@pytest.fixture
def run_committer(e2e_settings) -> Callable[..., subprocess.CompletedProcess]:
    """在本機以 committer-test 身分執行提交流程 (python -m aistorage.committer run)。"""
    cfg_path = str(e2e_settings["committer_config_path"])

    def _execute(*, dry_run: bool = False, force_full: bool = False) -> subprocess.CompletedProcess:
        cmd = ["uv", "run", "python", "-m", "aistorage.committer", "run", "--config", cfg_path]
        if dry_run:
            cmd.append("--dry-run")
        if force_full:
            cmd.append("--full-rebuild")
        res = subprocess.run(cmd, cwd=str(REPO_ROOT), capture_output=True, text=True)
        if res.returncode != 0:
            raise RuntimeError(f"Committer 執行失敗 (rc={res.returncode}):\nSTDOUT: {res.stdout}\nSTDERR: {res.stderr}")
        return res

    return _execute


@pytest.fixture
def e2e_reader(e2e_settings) -> AgoraReader:
    """透過產生的 reader.e2e.json 建立正式的 AgoraReader 讀取介面。"""
    from aistorage.drive import HttpDriveClient, RcloneConfToken

    cfg_path = e2e_settings["reader_config_path"]
    reader_cfg = ReaderConfig.load(cfg_path)

    # 以 reader 設定中的憑證建立 Drive 用戶端
    drive = HttpDriveClient(RcloneConfToken(reader_cfg.sa_key_path))
    rv_client = ReadViewClient(drive, reader_cfg)
    return AgoraReader(rv_client)


class ResidentContainerHandle:
    """管理個別住民容器的生命週期與互動。"""

    def __init__(self, name: str, port: int, work_dir: Path, model: str):
        self.name = name
        self.port = port
        self.work_dir = work_dir
        self.model = model
        self.proc: subprocess.Popen | None = None

    @property
    def api_url(self) -> str:
        return f"http://127.0.0.1:{self.port}"

    def wait_ready(self, timeout: float = 30.0) -> None:
        """等待容器內 opencode serve 就緒。"""
        deadline = time.time() + timeout
        while time.time() < deadline:
            try:
                req = urllib.request.Request(f"{self.api_url}/session", headers={"Accept": "application/json"})
                with urllib.request.urlopen(req, timeout=2) as resp:
                    if resp.status == 200:
                        return
            except Exception:
                time.sleep(0.5)
        raise TimeoutError(f"住民容器 {self.name} 在 {timeout} 秒內未就緒 (port {self.port})")

    def prompt(self, text: str, *, session_id: str | None = None) -> dict[str, Any]:
        """向容器內的 opencode 送出提示詞（要求呼叫 aistorage_* 工具）。"""
        payload = json.dumps({"prompt": text, "session_id": session_id}).encode("utf-8")
        req = urllib.request.Request(
            f"{self.api_url}/prompt",
            data=payload,
            headers={"Content-Type": "application/json"},
            method="POST",
        )
        with urllib.request.urlopen(req, timeout=60) as resp:
            return json.loads(resp.read().decode("utf-8"))

    def list_sessions(self) -> list[dict[str, Any]]:
        """取得容器內既有的 opencode sessions。"""
        req = urllib.request.Request(f"{self.api_url}/session", headers={"Accept": "application/json"})
        with urllib.request.urlopen(req, timeout=10) as resp:
            return json.loads(resp.read().decode("utf-8"))

    def stop(self) -> None:
        """停止並強制移除容器。"""
        subprocess.run(["docker", "rm", "-f", self.name], capture_output=True)
        if self.proc:
            self.proc.terminate()
            try:
                self.proc.wait(timeout=5)
            except subprocess.TimeoutExpired:
                self.proc.kill()


@pytest.fixture
def resident_pool(e2e_settings, tmp_path) -> Generator[Callable[..., ResidentContainerHandle], None, None]:
    """建立並追蹤測試中啟動的所有住民容器，並於 session 結束時清理。"""
    active_containers: list[ResidentContainerHandle] = []
    base_port = 4100

    def _spawn(name: str, *, profile: str = "mac-opencode", port_offset: int = 0) -> ResidentContainerHandle:
        port = base_port + len(active_containers) + port_offset
        work_dir = tmp_path / "work" / name
        work_dir.mkdir(parents=True, exist_ok=True)
        model = e2e_settings["model"]

        # 啟動 resident/run.sh 並發布 API 埠供測試驅動
        cmd = [
            str(RUN_SH),
            name,
            "--profile",
            profile,
            "--model",
            model,
            "--publish-api",
            str(port),
            "--no-tui",
        ]
        proc = subprocess.Popen(cmd, cwd=str(REPO_ROOT), stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        handle = ResidentContainerHandle(name=name, port=port, work_dir=work_dir, model=model)
        handle.proc = proc
        active_containers.append(handle)
        handle.wait_ready()
        return handle

    try:
        yield _spawn
    finally:
        for c in active_containers:
            try:
                c.stop()
            except Exception:
                pass
